name: Setup Environment
description: Setup Node Environment
author: July

branding:
  icon: package
  color: orange

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/

    - name: Setup Pnpm
      uses: pnpm/action-setup@v4

